### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by ShebangDog** [RTBMBuildUp/GurumeNaviApp#1]
アプリのライフサイクルに合わせて、位置情報を取得する。

**Comment by ShebangDog** [comment]
thisの扱い方を一つに決める
採用度の高いものから順に


- 使える箇所では絶対に使う
- 左辺または処理を表す場合にのみ使う


の２つがありそれぞれのメリット、デメリットは以下である

### 使える箇所では絶対に使う
**メリット**
- IDEの補完を最大限に活かせる
- ルールがシンプル、覚えやすい

**デメリット** 
- 見た目に違和感あり、特に右辺にあるthis(個人的なものであるし、理由は謎

### 左辺または処理を表す場合にのみ使う
**メリット**
- 見た目の違和感が減る(はず 

**デメリット**
- IDEの補完でカバーできる部分を諦めることになりうる

**Comment by ShebangDog** [comment]
ListView内にRestaurantIdの情報を持たせて、データの受け渡しをListViewで完結させる

**Comment by ShebangDog** [comment]
ifPresentOrDefaultの追加

**Comment by ShebangDog** [comment]
標準出力をlogへ切り替える、優先順位は低いがtimberを使ってデバッグ時の出力も消せるようにする

**Comment by ShebangDog** [comment]
完了したらhoorayを押していく

**Comment by RTBMBuildUp** [comment]
> thisの扱い方を一つに決める
> 採用度の高いものから順に
> 
>     * 使える箇所では絶対に使う
> 
>     * 左辺または処理を表す場合にのみ使う
> 
> 
> の２つがありそれぞれのメリット、デメリットは以下である
> ### 使える箇所では絶対に使う
> 
> **メリット**
> 
>     * IDEの補完を最大限に活かせる
> 
>     * ルールがシンプル、覚えやすい
> 
> 
> **デメリット**
> 
>     * 見た目に違和感あり、特に右辺にあるthis(個人的なものであるし、理由は謎
> 
> 
> ### 左辺または処理を表す場合にのみ使う
> 
> **メリット**
> 
>     * 見た目の違和感が減る(はず
> 
> 
> **デメリット**
> 
>     * IDEの補完でカバーできる部分を諦めることになりうる

現時点では**左辺または処理を表す場合にのみ使う**を採用

**Comment by ShebangDog** [comment]
Inkscapeを使ってアイコンを描く

**Comment by ShebangDog** [comment]
> 標準出力をlogへ切り替える、優先順位は低いがtimberを使ってデバッグ時の出力も消せるようにする

標準出力からlogへの切り替えは完了した。
timberの利用はまだ。

**Comment by RTBMBuildUp** [comment]
> > 標準出力をlogへ切り替える、優先順位は低いがtimberを使ってデバッグ時の出力も消せるようにする
> 
> 標準出力からlogへの切り替えは完了した。
> timberの利用はまだ。
